package com.kitchencabinet.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors (from JS :root)
val LightBackground = Color(0xFFFBF9F8)
val LightForeground = Color(0xFF1B1C1C)
val LightSurface = Color(0xFFFBF9F8)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF6F3F2)
val LightSurfaceContainer = Color(0xFFF0EDED)
val LightSurfaceContainerHigh = Color(0xFFEAE7E7)
val LightOnSurfaceVariant = Color(0xFF56423D)
val LightOutline = Color(0xFF89726C)
val LightOutlineVariant = Color(0xFFDCC0BA)
val LightCard = Color(0xFFFFFFFF)
val LightPrimary = Color(0xFF9A4028)
val LightPrimaryForeground = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBA573E)
val LightSecondary = Color(0xFF56642B)
val LightSecondaryForeground = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD6E7A1)
val LightTertiary = Color(0xFFD6E7A1)
val LightTertiaryForeground = Color(0xFF5A682F)
val LightDestructive = Color(0xFFBA1A1A)
val LightDestructiveForeground = Color(0xFFFFFFFF)
val LightSuccess = Color(0xFF56642B)
val LightBorder = Color(0xFFE4E2E1)

// Dark theme colors (from JS .dark)
val DarkBackground = Color(0xFF1B1C1C)
val DarkForeground = Color(0xFFF3F0F0)
val DarkSurface = Color(0xFF1B1C1C)
val DarkSurfaceContainerLowest = Color(0xFF0F1010)
val DarkSurfaceContainerLow = Color(0xFF232424)
val DarkSurfaceContainer = Color(0xFF2A2B2B)
val DarkSurfaceContainerHigh = Color(0xFF303132)
val DarkOnSurfaceVariant = Color(0xFFD8C2BC)
val DarkOutline = Color(0xFFA08A83)
val DarkOutlineVariant = Color(0xFF56423D)
val DarkCard = Color(0xFF2A2B2B)
val DarkPrimary = Color(0xFFFFB4A2)
val DarkPrimaryForeground = Color(0xFF3C0800)
val DarkPrimaryContainer = Color(0xFF7E2B16)
val DarkSecondary = Color(0xFFBDCE89)
val DarkSecondaryForeground = Color(0xFF161F00)
val DarkSecondaryContainer = Color(0xFF3E4C16)
val DarkTertiary = Color(0xFF3E4C16)
val DarkTertiaryForeground = Color(0xFFD6E7A1)
val DarkDestructive = Color(0xFFFFB4AB)
val DarkDestructiveForeground = Color(0xFF690005)
val DarkSuccess = Color(0xFFBDCE89)
val DarkBorder = Color(0xFF3A3A3A)
